### ISSUE TITLE
user and password not working

### ISSUE THREAD

**Issue by sagivf** [wayann/logstash-input-rethinker#1]
I think it's missing in - https://github.com/wayann/logstash-input-rethinker/blob/master/lib/logstash/inputs/rethinker.rb#L58

It's defined, but never used:
https://github.com/wayann/logstash-input-rethinker/blob/master/lib/logstash/inputs/rethinker.rb#L38

Thanks

**Comment by wayann** [comment]
yes, please make a pull request and I'll commit

**Comment by sagivf** [comment]
Added - https://github.com/wayann/logstash-input-rethinker/pull/3

**Comment by sagivf** [comment]
@wayann the pull request is bad 😞 
I ran it (actually ran the original 2.x repo) and got `Error: Cannot specify both a password and an auth key. {:level=>:error}` so apparently theres a need to be some sort of if statement that will only pass one of them (I think the password should supersede) to the connection. I made a test removing the auth_key property and it worked 😄 

I don't know ruby so it would take me a while to get that rolling. Any chance you could do it? I can test it immediately...

**Comment by wayann** [comment]
@sagivf done, check if it's working like this for you.

**Comment by sagivf** [comment]
@wayann yep, it works 👍 thanks for the quick turnaround man 🥇
