### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by sagivf** [wayann/logstash-input-rethinker#4]
I'm not a ruby guy, but if I understand correctly it's sort of like doing an `npm publish`, isn't it?
Couldn't we just publish this ?
https://www.elastic.co/guide/en/logstash/current/private-rubygem.html

**Comment by wayann** [comment]
I've published this plugin to rubygems.org so basically logstash should install directly with
`bin/plugin install logstash-input-rethinker`
