### ISSUE TITLE
watch_dbs not working (I think)

### ISSUE THREAD

**Issue by norpan** [wayann/logstash-input-rethinker#5]
Hi,
I'm running the plugin and it works great when I watch tables that already exist. However, the watch_dbs does not seem to work. I'm running an example with the default settings, and I have a table test.bar, but no test.foo. I start logstash, add the table foo, and insert the document {a:1} into both test.bar and test.foo, but it only sees the addition to test.bar.

Maybe I've misunderstood how watch_dbs is supposed to work?

I've attached the log file for logstash.
[logstash.txt](https://github.com/wayann/logstash-input-rethinker/files/1364600/logstash.txt)

**Comment by wayann** [comment]
Hi @norpan, I don't think watch_dbs is meant to be used that way....

**Comment by norpan** [comment]
Well, that may well be true, but how is it meant to be used then?

**Comment by wayann** [comment]
I do suspect it expect that you create the db and tables before, not at runtime, but sincerely I've never tried your way, so I may be wrong..
good luck! :)
